version: 2
updates:
  - package-ecosystem: mix
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 999
  - package-ecosystem: mix
    directory: "/bench"
    schedule:
      interval: weekly
      day: sunday
    open-pull-requests-limit: 999
  - package-ecosystem: github-actions
    directory: "/"
    schedule:
      interval: weekly
      day: sunday
