name: Test suite

on:
  push:
    branches:
      - main
  pull_request:

jobs:
  build:
    name: Test (${{matrix.elixir}}/${{matrix.otp}})
    runs-on: ubuntu-latest
    strategy:
      matrix:
        otp: [24.x, 25.x, 26.x, 27.x]
        elixir: [1.12.x, 1.13.x, 1.14.x, 1.15.x, 1.16.x, 1.17.x]
        exclude:
          - otp: 27.x
            elixir: 1.16.x
          - otp: 27.x
            elixir: 1.15.x
          - otp: 27.x
            elixir: 1.14.x
          - otp: 27.x
            elixir: 1.13.x
          - otp: 27.x
            elixir: 1.12.x
          - otp: 26.x
            elixir: 1.13.x
          - otp: 26.x
            elixir: 1.12.x
          - otp: 25.x
            elixir: 1.13.x
          - otp: 25.x
            elixir: 1.12.x
          - otp: 24.x
            elixir: 1.17.x
    steps:
      - uses: actions/checkout@v5
      - uses: erlef/setup-beam@v1
        with:
          elixir-version: ${{ matrix.elixir }}
          otp-version: ${{ matrix.otp }}
      - name: Restore dependencies cache
        uses: actions/cache@v4
        with:
          path: deps
          key: |
            ${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-mix-

      - name: Install Dependencies
        run: mix deps.get

      - name: Run Tests
        run: mix test

  lint:
    runs-on: ubuntu-latest
    name: Linting
    strategy:
      matrix:
        elixir: ["1.17"]
        otp: ["27"]
    steps:
      - uses: actions/checkout@v5
      - uses: erlef/setup-beam@v1
        id: beam
        with:
          otp-version: ${{ matrix.otp }}
          elixir-version: ${{ matrix.elixir }}
      - name: Build cache
        uses: actions/cache@v4
        with:
          path: |
            deps
            _build
          key: |
            ${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-mix-${{ hashFiles('**/mix.lock') }}
          restore-keys: |
            ${{ runner.os }}-${{ steps.beam.outputs.otp-version }}-${{ steps.beam.outputs.elixir-version }}-mix-
      - run: mix deps.get
      - run: mix deps.unlock --check-unused
      - run: mix compile --warnings-as-errors
      - run: mix format --check-formatted
